name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
        
    - name: Check out code
      uses: actions/checkout@v1
      
    - name: Build golang binary
      run: |
        make build_linux_amd64
    
    - name: Build docker
      run: |
        docker build -t cody0704/autorpm .
        docker tag docker.pkg.github.com/cody0704/autorpm/auto-rpm:latest cody0704/autorpm:1.0
    
    - name: Push
      run: |
        docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/cody0704/autorpm/auto-rpm:latest
        docker push docker.pkg.github.com/cody0704/autorpm/auto-rpm:1.0